version: '3.8'
services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test-brain
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/data/postgres'
  
  app:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=test-brain
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: npm run start:prod

volumes:
  postgres:
  app:


